version: '3.3'
services:
  bitcoind1:
    image: polarlightning/bitcoind:23.0
    container_name: polar-n1-bitcoind1
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: bitcoind1
    command: >-
      bitcoind -server=1 -regtest=1
      -rpcauth=polaruser:5e5e98c21f5c814568f8b55d83b23c1c$$066b03f92df30b11de8e4b1b1cd5b1b4281aa25205bd57df9be82caf97a05526
      -debug=1 -zmqpubrawblock=tcp://0.0.0.0:28334
      -zmqpubrawtx=tcp://0.0.0.0:28335 -zmqpubhashblock=tcp://0.0.0.0:28336
      -txindex=1 -dnsseed=0 -upnp=0 -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0
      -rpcport=18443 -rest -listen=1 -listenonion=0 -fallbackfee=0.0002
    volumes:
      - ./volumes/bitcoind/bitcoind1:/home/bitcoin/.bitcoin
    expose:
      - '18443'
      - '18444'
      - '28334'
      - '28335'
    ports:
      - '18443:18443'
      - '19444:18444'
      - '28334:28334'
      - '29335:28335'
  bryan:
    image: polarlightning/lnd:0.15.2-beta
    container_name: polar-n1-bryan
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: bryan
    command: >-
      lnd --noseedbackup --trickledelay=5000 --alias=bryan --externalip=bryan
      --tlsextradomain=bryan --tlsextradomain=polar-n1-bryan
      --listen=0.0.0.0:9735 --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080
      --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=polar-n1-bitcoind1 --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://polar-n1-bitcoind1:28334
      --bitcoind.zmqpubrawtx=tcp://polar-n1-bitcoind1:28335
    restart: always
    volumes:
      - ./volumes/lnd/bryan:/home/lnd/.lnd
    expose:
      - '8080'
      - '10009'
      - '9735'
    ports:
      - '8081:8080'
      - '10001:10009'
      - '9735:9735'
  jordan:
    image: polarlightning/lnd:0.15.2-beta
    container_name: polar-n1-jordan
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: jordan
    command: >-
      lnd --noseedbackup --trickledelay=5000 --alias=jordan --externalip=jordan
      --tlsextradomain=jordan --tlsextradomain=polar-n1-jordan --listen=0.0.0.0:9735
      --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080 --bitcoin.active
      --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=polar-n1-bitcoind1 --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://polar-n1-bitcoind1:28334
      --bitcoind.zmqpubrawtx=tcp://polar-n1-bitcoind1:28335
    restart: always
    volumes:
      - ./volumes/lnd/jordan:/home/lnd/.lnd
    expose:
      - '8080'
      - '10009'
      - '9735'
    ports:
      - '8082:8080'
      - '10002:10009'
      - '9736:9735'
  stephen:
    image: polarlightning/lnd:0.15.2-beta
    container_name: polar-n1-stephen
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: stephen
    command: >-
      lnd --noseedbackup --trickledelay=5000 --alias=stephen --externalip=stephen
      --tlsextradomain=stephen --tlsextradomain=polar-n1-stephen
      --listen=0.0.0.0:9735 --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080
      --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=polar-n1-bitcoind1 --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://polar-n1-bitcoind1:28334
      --bitcoind.zmqpubrawtx=tcp://polar-n1-bitcoind1:28335
    restart: always
    volumes:
      - ./volumes/lnd/stephen:/home/lnd/.lnd
    expose:
      - '8080'
      - '10009'
      - '9735'
    ports:
      - '8083:8080'
      - '10003:10009'
      - '9737:9735'
  john:
    image: polarlightning/lnd:0.15.2-beta
    container_name: polar-n1-john
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: john
    command: >-
      lnd --noseedbackup --trickledelay=5000 --alias=john --externalip=john
      --tlsextradomain=john --tlsextradomain=polar-n1-john
      --listen=0.0.0.0:9735 --rpclisten=0.0.0.0:10009 --restlisten=0.0.0.0:8080
      --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind
      --bitcoind.rpchost=polar-n1-bitcoind1 --bitcoind.rpcuser=polaruser
      --bitcoind.rpcpass=polarpass
      --bitcoind.zmqpubrawblock=tcp://polar-n1-bitcoind1:28334
      --bitcoind.zmqpubrawtx=tcp://polar-n1-bitcoind1:28335
    restart: always
    volumes:
      - ./volumes/lnd/john:/home/lnd/.lnd
    expose:
      - '8080'
      - '10009'
      - '9735'
    ports:
      - '8084:8080'
      - '10004:10009'
      - '9738:9735'
